d = dict({100: 'narsi', 200: 'sai'})
print(d)
d = dict([(100, 'vignesh'), (200, 'rajesh')])
print(d)
print(len(d))
print(d.get(100))
print(d.get(500))
print(d.get(500, 'victor'))
print(d.keys())
print(d.values())
print(d.items())

for k, v in d.items():
    print(k, '....', v)

d1 = d.copy()
print(d1)
print(d1.setdefault(400, 'hari'))
print(d1)
print(d.pop(100))
print(d.popitem())
d.update(d1)
print(d)
d1.update([(555, 'yuvi')])
print(d1)
